= Homepi
:page-aliases: it::homepi.adoc

Der Homepi ist der zentrale Server im lokalen Netzwerk. Er befindet sich im Keller auf dem "Netzwerkschrank". 

== Hardware

Beim Homepi handelt es sich aktuell um einen link:https://www.raspberrypi.org/products/raspberry-pi-5-model-b/[Raspberry Pi 5 B] mit 8 GB RAM.
Zur besseren Ausfallsicherheit ist der Homepi mit einer SSD als Festplatte ausgestattet. Das ist schneller und zuverlässiger als eine SD-Karte.
Außerdem sind direkt an den Homepi noch Schnittstellen für verschiedene Smart Home Systeme angeschlossen. Details dazu auf der Seite xref:it/services/smart_home/index.adoc[Smart Home].

== USB Geräte

Der Raspberry bekommt vom Netzteil 5000 mA. Selbst braucht er maximal 2500 mA. Bleiben noch ca. 2500 mA für Geräte.

|===
|Gerät |Modell |Stromverbrauch

|NVME Shield
|https://wiki.geekworm.com/X1001[Geekworm X1001]
|0 mA

|SSD
|https://www.sandisk.com/de-de/products/ssd/internal-ssd/wd-blue-sn5000-nvme-ssd?sku=WDS100T4B0E-00CNZ0[WD Blue SN5000/1TB]
|420 mA

|Zigbee Stick
|link:https://zig-star.com/projects/zigbee-stick-v4/[Zigstar Zigbee Stick v4]
|60 mA

|HomeMatic IP Stick
|https://de.elv.com/p/elv-arr-bausatz-homematic-ip-rf-usb-stick-fuer-alternative-steuerungsplattformen-hmip-rfusb-P152306/[HmIP-RFUSB]
|?? mA

|USB Hub
|
|?? mA

|===

== Notfall Reboot

Sollte der Homepi nicht mehr reagieren kann man die Stromversorgung über die vorgeschaltete Netzwerksteckdose trennen und neu verbinden.
Dafür muss der Befehl `curl http://<ip>/switch/relay/turn_off -X POST` gefolgt von `curl http://<ip>/switch/relay/turn_on -X POST` auf z.B. dem Router ausgeführt werden.
Die IP der Steckdose findet sich im vaultwarden unter "powerplug01".

== Netzwerk

Der Homepi ist mit einem Kabel mit dem Router verbunden.
Per SSH ist der Host sowohl von innerhalb des Netztes als auch aus dem Internet unter dem Host +homepi.bergmann.click+ zu erreichen. Die Zugangsdaten befinden sich im vaultwarden. 

== Software

=== Betriebssystem

Aktuell läuft auf dem Homepi ein Raspbian 10.

=== Services

Folgende Dienste laufen auf dem Homepi:

|===
|Dienst |Software |Config-File |Details

|link:https://hass.bergmann.click[Smart Home Zentrale]
|link:https://www.home-assistant.io/[Home Assistant]
|+/home/homeassistant/.homeassistant/configuration.yaml+
|xref:it/services/smart_home/index.adoc[Smart Home]

|Zabbix Proxy
|link:https://www.zabbix.org[Zabbix] Proxy
|+/etc/zabbix/zabbix_proxy.conf+
|xref:it/services/monitoring.adoc[Monitoring]

|Zabbix Agent
|link:https://www.zabbix.org[Zabbix] Agent
|+/etc/zabbix/zabbix_agent2.conf+
|xref:it/services/monitoring.adoc[Monitoring]

|Unifi Proxy for Monitoring
|link:https://github.com/zbx-sadman/unifi_proxy[Unifi Proxy]
|+/etc/unifi_proxy/unifi_proxy.conf+
|xref:it/services/monitoring.adoc[Monitoring]

|Syslog Daemon
|link:https://www.rsyslog.com/doc[rsyslogd]
|+/etc/rsyslog.conf+
|xref:it/services/monitoring.adoc[Monitoring]

|Radius Server für Wifi
|link:https://freeradius.org[freeRADIUS]
|+/etc/freeradius/3.0/radiusd.conf+
|xref:it/services/wifi.adoc[Wifi]

|link:https://unifi.bergmann.click[Wifi Controller]
|link:https://www.ui.com/software/[Unifi Controller]
|+/var/lib/unifi+
|xref:it/services/wifi.adoc[Wifi]

|Kubernetes Node
|link:https://k3s.io/[k3s]
|
|xref:k8s::index.adoc[K8S]

|===
