= Smart Home

Zur Automatisierung und bequemen Steuerung der Funktionen unseres Hauses (z.B Licht, Heizung, etc.) sind einige der Komponenten "smart".
Das bedeutet sie können elektronisch ferngesteuert werden.

== Zentrale

Bei der Erstellung dieses Smart-Homes war es mein Bestreben, dass so wenige Daten wie möglich nach außen gelangen.
Daher werden alle Geräte lokale vom xref:homepi.adoc[Homepi] und daran angeschlossenen Schnittstellen gesteuert.
Zur Verwaltung und Steuerung verwenden wir die Software link:https://home-assistant.io[Home Assistant] welche unter https://hass.bergmann.click sowohl von innerhalb als auch aus dem Internet erreichbar ist. Jedes Familienmitglied hat seinen eigenen Zugang mit verschiedenen Rechten.
Zur Benennung der Entities und Devices im Home Assistant siehe xref:services/smart_home/naming.adoc[Smart Home Naming].
Außerdem ist es wichtig, dass die wichtigsten Funktionen (Licht, Rolläden) auch ohne die Zentrale funktionieren. So sind z.B. die Lichter in Gruppen welche direkt über Zigbee von den Fernbedinungen gesteuert werden. So funktionieren die Lichtschalter auch wenn die Zentrale ausfällt.


== Zigbee

Einige der Komponenten sind per link:https://de.wikipedia.org/wiki/ZigBee[Zigbee] vernetzt.
Dazu ist am Homepi ein link:https://zig-star.com/projects/zigbee-stick-v4/[Zigstar Zigbee Stick v4] USB Stick angeschlossen der als Zentrale des Zigbee Netztes dient.
Neue Komponenten können über die link:https://www.zigbee2mqtt.io/[Zigbee2MQTT] welche unter https://zigbee.bergmann.click erreichbar ist hinzugefügt werden.
Ebenso können dort Gruppen mit Schalter und Bewegungsmelder-Konfigurtionen verwaltet werden. Diese Geräte tauchen dann als Entities in Home Assistant auf.

Aktuell sind folgende Geräte so angeschlossen:

=== Lampen und Schalter

Fast alle Leuchtmittel im Haus sind "smarte" Leuchtmittel aus der Serie link:https://www.ikea.com/de/de/cat/ikea-home-smart-beleuchtung-36812/["Tradfri"] von IKEA.
Ebenso finden sich im Haus die entsprechenden Schalter, Dimmer und Bewegungsmelder von Tradfri.

=== Thermometer/Luftqualität

In jedem Zimmer wird die Temparatur über die Thermostate gemessen.
In fast allen Zimmern ist zusätzlich ein link:https://www.amazon.de/dp/B07SB2C327[Aquara Multisensor angebracht]. Dieser misst Temparatur, Luftfeuchte und Luftdruck.

=== Thermostate

An den Heizkörpern im Haus sind link:https://www.zigbee2mqtt.io/devices/TV02-Zigbee.html[TuYa TV02-Zigbee] angeschlossen. Diese können sowohl die Temparatur messen als auch steuern.

=== Rolläden

An den Fenstern sind elektrische Rolläden verbaut. An jedem Rolladen ist ein link:https://www.zigbee2mqtt.io/devices/MS-108ZR.html[Moes MS-108ZR] angeschlossen. Neben der Steuerung über die Hausautomatisierung ist bei allen Rolläden auch eine Funk-Ferbedienung angelernt. Diese funktioniert unabhängig von der Zentrale.

== Wifi

Einige Komponenten sind direkt per xref:services/wifi.adoc[wlan] angeschlossen. 

=== Smarte Steckdosen

WLAN Steckdosen sind häufig günstiger als Z-wave oder Zigbee Steckdosen.
Daher haben wir zwei link:https://www.amazon.de/dp/B089LRRZNN[dieser Steckdosen].
Auf den Steckdosen wurde link:https://esphome.io[ESPHome] entsprechend link:https://frenck.dev/calibrating-an-esphome-flashed-power-plug/[dieser Anleitung] installiert.
Das hat außerdem den Vorteil, dass diese auch erreichbar sind wenn der xref:homepi.adoc[Homepi] nicht funktioniert. Damit kann dieser im xref:homepi.adoc#_notfall_reboot[Notfall rebootet werden].

=== Haustür

Diese ist indirekt über ein Shelly angeschlossen. Details siehe xref:services/zutritt.adoc[Zutritt].

Außerdem sind innen rund um die Glasscheibe der Haustür 144 link:https://www.amazon.de/gp/product/B01MYV70NJ[SK6812 RGBW-LEDS] verbaut. Diese werden von einem link:https://www.amazon.de/gp/product/B071ZCZJYK/[entsprechenden Netzteil] im Keller mit Strom versorgt und von einem link:https://www.amazon.de/gp/product/B0C4STTYRM[SP511E LED Controller] gesteuert. Auf diesem ist link:https://kno.wled.ge/[WLED] installiert und er ist unter http://192.168.2.184/ erreichbar.

=== Heizung

Der Primärenergiebedarf des Gebäudes wird durch einen Gast-Brennwertkessel im Keller abgedeckt. Diese bedient sowohl den einen Heizkreis als auch die Warmwasserbereitung. Letztere wird durch ein Solarthermie-Modul auf dem Dach unterstützt.

Die Gesamtanlage ist ein link:https://polo.broetje.de/pdfreqdoku.php?fn=ti_solar_d_low.pdf&ty=DE[Solarsystem W 300-2W] der Firma Brötje. Diese ist aus den folgenden Komponenten aufgebaut:

|===
|Komponente |Modell |Bemerkung

|Brennwertkessel
|link:https://polo.broetje.de/select.php?cat=4&dev=286[EcoTherm Plus WGB 20 C]
|

|Solarsteuerung
|link:https://polo.broetje.de/select.php?cat=11&dev=167[SOR S]
|

|Solarkollektoren
|link:https://polo.broetje.de/select.php?cat=11&dev=165&sort=9[FK 26 W]
|2 Stück

|Solarpumpe
|link:https://polo.broetje.de/select.php?cat=11&dev=167&sort=9[SPS 1.13]
|

|Solarspeicher
|link:https://polo.broetje.de/select.php?cat=11&dev=63[SSB 300 ECO]
|300 Liter


|===

An der Zentralheizung ist ein link:https://1coderookie.github.io/BSB-LPB-LAN/[BSB-LAN] Adapter angeschlossen. Dieser ist über http://192.168.2.187/ erreichbar und hierüber können verschiedene Parameter der Heizung ausgelesen und konfiguriert werden.

INFO: Aktuell werden hier nur Daten ausgelesen und gespeichert. Es gibt noch keine Automatisierung z.B. der Nachtabsenkung.

== Homematic IP

Für die Rauchmelder befindet sich am Homepi ein link:https://de.elv.com/elv-homematic-komplettbausatz-funkmodul-fuer-raspberry-pi-hm-mod-rpi-pcb-fuer-smart-home-hausautomation-142141[Homematic IP Modul].

=== Rauchmelder

Im Haus Verteilt befinden sich 10 link:https://www.amazon.de/dp/B01KPM3P68[Homematic IP Rauchmelder]. Diese sind untereinander unabhängig von der Zentrale vernetzt.

== Sprachsteuerung

Um die Smart-Home Geräte auch per Sprache steuern zu können ist eine Alexa Anbindung entsprechend link:https://www.home-assistant.io/integrations/alexa.smart_home/[dieser Anleitung] konfiguriert. 
