= Minecraft Server

Zum gemeinsamen Spielen von Minecraft haben wir einen entsprechenden Server.
Aus Leistungsgründen läuft dieser nicht auf dem xref:homepi.adoc[Homepi] sondern auf Christianes Desktop Rechner.

Alle Dateien des Servers sind unter +c:\minecraft_mcss+ zu finden.
Der Server ist sowohl aus dem internet Netz als auch aus dem Internet unter +minecraft.bergmann.click+ erreichbar.
Es sind verschiedene Welten verfügbar.
Die verschiedenen Server werden mit der Software link:https://www.mcserversoft.com[MC Server Soft] verwaltet.
Wenn die Software gestartet wird startet automatisch der Lobby Server und der Proxy. Die konkreten Welten können dann in MCSS gestartet werden.
Verbindet man sich mit dem Server kommt man immer in die Lobby und kann dann über Portal in die konkrete Welt wechseln.

== Remote Starten

Damit man auch spielen kann, wenn man z.B. im Urlaub ist, ist der Rechner so konfiguriert, dass man ihn auch von remote starten kann.
Dazu geht man wie folgt vor:

. Verbinden per ssh mit dem xref:homepi.adoc[Homepi].
. Den Rechner per etherwake aufwecken: +etherwake 70:85:c2:bd:8c:0e+
. Per link:https://teamviewer.com[Teamviewer] verbinden. Zugansdaten sind unter "Teamviewer neuesding" im 1password.
. Login mit einem User.
. Starten von MCSS über den Startmenü-Eintrag.

NOTE: Um das Spiel nicht zu unterbrechen wird die Stromsparfunktion des Rechners beim Start des Servers abgeschaltet. Daher ist es wichtig, nach dem Spiel den Server zu stoppen und den Rechner herunter zu fahren um Strom zu sparen.
