= Minecraft Server

Zum gemeinsamen Spielen von Minecraft haben wir einen entsprechenden Server.
Aus Leistungsgründen läuft dieser nicht auf dem xref:homepi.adoc[Homepi] sondern auf Christianes Desktop Rechner.

Alle Dateien des Servers sind unter +c:\minecraft_server+ zu finden.
Der Server ist sowohl aus dem internet Netz als auch aus dem Internet unter +minecraft.bergmann.click+ erreichbar.
Es sind verschiedene Welten verfügbar.
Für jede Welt gibt es eine bat Datei welche den Server für die Welt vorbereitet (Konfigurationsdatei kopiert), die Stromsparfunktion des Computers ausschaltet und den Server startet. 

== rcon

Der Server horcht auf Port +25575+ auf das minecraft rcon Protokoll. Das Passwort findet sich unter "Minecraft Server Rcon" im 1password.

== Remote Starten

Damit man auch spielen kann, wenn man z.B. im Urlaub ist, ist der Rechner so konfiguriert, dass man ihn auch von remote starten kann.
Dazu geht man wie folgt vor:

. Verbinden per ssh mit dem xref:homepi.adoc[Homepi].
. Den Rechner per etherwake aufwecken: +etherwake 70:85:c2:bd:8c:0e+
. Per link:https://teamviewer.com[Teamviewer] verbinden. Zugansdaten sind unter "Teamviewer neuesding" im 1password.
. Login mit einem User.
. Starten des entsprechenden Servers mittels z.b. +c:\minecraft_server\dorfleben.bat+.

NOTE: Um das Spiel nicht zu unterbrechen wird die Stromsparfunktion des Rechners beim Start des Servers abgeschaltet. Daher ist es wichtig, nach dem Spiel den Server zu stoppen und den Rechner herunter zu fahren um Strom zu sparen.
