site:
  title: Bergmann Infrastruktur Dokumentation
  url: https://doku.bergmann.click
  start_page: allgemeines::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_paths: 
      - it
      - allgemeines
  - url: ../homepi-cluster
    branches: HEAD
    start_paths: 
      - docs
  - url: ../doku-aschaffenburg
    branches: HEAD
runtime: 
  fetch: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output: 
  clean: true 
  dir: ../doku.bergmann.click
asciidoc:
  extensions:
    - asciidoctor-kroki
    - asciidoctor-emoji
