= Smart Home

Zur Automatisierung und bequemen Steuerung der Funktionen unseres Hauses (z.B Licht, Heizung, etc.) sind einige der Komponenten "smart".
Das bedeutet sie können elektronisch ferngesteuert werden.

== Zentrale

Bei der Erstellung dieses Smart-Homes war es mein Bestreben, dass so wenige Daten wie möglich nach außen gelangen.
Daher werden alle Geräte lokale vom xref:homepi.adoc[Homepi] und daran angeschlossenen Schnittstellen gesteuert.
Zur Verwaltung und Steuerung verwenden wir die Software link:https://home-assistant.io[Home Assistant] welche unter https://hass.bergmann.click sowohl von innerhalb als auch aus dem Internet erreichbar ist. Jedes Familienmitglied hat seinen eigenen Zugang mit verschiedenen Rechten.
Zur benennung der Entities und Devices im Home Assistant siehe xref:services/smart_home/naming.adoc[Smart Home Naming].

== Zigbee

Einige der Komponenten sind per link:https://de.wikipedia.org/wiki/ZigBee[Zigbee] vernetzt.
Dazu ist am Homepi ein link:https://www.phoscon.de/de/conbee2[conbee II] USB Stick angeschlossen der als Zentrale des Zigbee Netztes dient.
Neue Komponenten können über die link:https://phoscon.de/de/app/doc[Phoscon App] welche unter https://deconz.bergmann.click erreichbar ist hinzugefügt werden.
Ebenso können dort Gruppen mit Schalter und Bewegungsmelder-Konfigurtionen verwaltet werden. Diese Geräte tauchen dann als Entities in Home Assistant auf.

Aktuell sind folgende Geräte so angeschlossen:

=== Lampen und Schalter

Fast alle Leuchtmittel im Haus sind "smarte" Leuchtmittel aus der Serie link:https://www.ikea.com/de/de/cat/ikea-home-smart-beleuchtung-36812/["Tradfri"] von IKEA.
Ebenso finden sich im Haus die entsprechenden Schalter, Dimmer und Bewegungsmelder von Tradfri.

=== Thermometer/Luftqualität

In jedem Zimmer wird die Temparatur über die Thermostate gemessen.
Da Leonards Heizkörper auf dem Zwischengeschoss zum Dachgeschoss ist kann es (vor allem im Sommer) vorkommen, dass die Temparatur zwischen Heizkörper und Zimmer recht stark abweicht.
Daher ist dort zusätzlich ein link:https://www.amazon.de/dp/B07SB2C327[Aquara Multisensor angebracht]. Dieser misst Temparatur, Luftfeuchte und Luftdruck.

=== Thermostate

An den Heizkörpern im Haus sind link:https://www.zigbee2mqtt.io/devices/TV02-Zigbee.html[TuYa TV02-Zigbee] angeschlossen. Diese können sowohl die Temparatur messen als auch steuern.

== Wifi

Einige Komponenten sind direkt per xref:services/wifi.adoc[wlan] angeschlossen. 

=== Smarte Steckdosen

WLAN Steckdosen sind häufig günstiger als Z-wave oder Zigbee Steckdosen.
Daher haben wir zwei link:https://www.amazon.de/dp/B089LRRZNN[dieser Steckdosen].
Auf den Steckdosen wurde link:https://esphome.io[ESPHome] entsprechend link:https://frenck.dev/calibrating-an-esphome-flashed-power-plug/[dieser Anleitung] installiert.
Das hat außerdem den Vorteil, dass diese auch erreichbar sind wenn der xref:homepi.adoc[Homepi] nicht funktioniert. Damit kann dieser im xref:homepi.adoc#_notfall_reboot[Notfall rebootet werden].

== Homematic IP

Für die Rauchmelder befindet sich am Homepi ein link:https://de.elv.com/elv-homematic-komplettbausatz-funkmodul-fuer-raspberry-pi-hm-mod-rpi-pcb-fuer-smart-home-hausautomation-142141[Homematic IP Modul].

=== Rauchmelder

Im Haus Verteilt befinden sich 10 link:https://www.amazon.de/dp/B01KPM3P68[Homematic IP Rauchmelder]. Diese sind untereinander unabhängig von der Zentrale vernetzt.

== Sprachsteuerung

Um die Smart-Home Geräte auch per Sprache steuern zu können ist eine xref:services/alexa.adoc[Alexa] Anbindung entsprechend link:https://www.home-assistant.io/integrations/alexa.smart_home/[dieser Anleitung] konfiguriert. 
