= IPv6

== ULA

Das ULA Netz fd6b:b175:9ccf::/48 wurde anhand der eth0 MAC-Adresse des Routers auf https://cd34.com/rfc4193/ generiert.

Für das xref:k8s::index.adoc[k8s Cluster] wurden zu verschiedenen Zeitpunkten anhand der eth0 MAC des ersten nodes die ULAs fd53:f3c0:fefd::/48 für das cluster-cidr und fde2:37f0:b85f::/48 für das service-cidr generiert.

== Prefix delegation

Wir bekommen vom Provier ein dynamisches /56 delegiert. Jedes der Subnetzte bekommt entsprechend der Subnet-ID ein /64 zugewiesen.

Das höchstwertige /58 wird für NAT-PT reserviert.

== NAT-PT

Da nicht alle Dienste mit dynamisch wechselnden Subnetzen zurecht kommen hat jedes Netz zusätzlich noch ein ULA Netz.

Wir reservieren den Bereich fd6b:b175:9ccf:0000::/56 entsprechend der deligierten Präfixgröße für NAT-PT.

Aktell nutzen wir aber nur das letzte /58 also fd6b:b175:9ccf:00c0/58 für NAT-PT. Dieses wird auf das oben genannten deligierte letzte /58 gemapped.

Um das beim Update des deligierten Netzes zu aktualisieren existiert ein link:https://github.com/bergmann-it/edgeos-scripts[Script].
