= Netzwerk

== Physikalisches Netzwerk
Das Netzwerk in der Frankensteiner Str. 15 ist relativ einfach um den Mittelpunkt im Kellerflur aufgebaut:

[svgbob]
....
------+---------------------------------------------------------------------------------------
2. OG |                                          
------'                                               
                                               
------+------------------------------+-+------+-------------------+-+-------+-----------------
1. OG |                              | | Flur | +-----------+     | | Buero | +---------+
------'                              | '------' | AP        |     | '-------' | Gelbes  |
                                     |          | 1. OG     +---. |           | Telefon +-.
                                     |          +-----------+   | |           +---------+ |
                                     |                          | |                       |
                                     |          +-------+       | | .--O                  |
                                     |          | DECT  |       | | |                     |
                                     |          | Basis +-------|-|-|-.                   |
                                     |          +-------+       | | | |                   |
                                     |                          | | | |                   |
---+---------------------------------+--------------------------+-+-+-+-------------------+---
EG |                                            +-----------+   |   | |                   |
---'                                            | AP        |   |   | |                   |
                                                | Garderobe +-. |   | |                   |
                                                +-----------+ | |   | |                   |
-------+------------+-+--------------+--+-+------+------------+-+---+-+-------------------+---
Keller |            | | Heizungsraum |  | | Flur |            | |   | |                   |
-------'            | '--------------'  | '------'            | |   | |                   |
    .-,(  ),-.      |    +-------+      |     +-----------+   | |   | |                   |
 .-(          )-.   |    | VDSL  |      |     |   Router  |   | |   | |                   |
(    internet    )--+----+ Modem |      |    ,+-         -+.  | |   | |  +---------+      |
 '-(          ).-'  |    |       +------+----+ eth0   eth4 +--' |   | |  | Switch  |      |
     '-.( ).-'      |    +-------+      |    `+-      eth3 +----'   | | ,+-        |      |
                    |                   |     |       eth1 +--------' `-+ port4   -+.     |
                    |                   |     |       eth2 +------------+ port1     +--.  |
                    |                   |     |          -+'  .---------+ port2   -+'  |  |
                    |                   |     +-----------+   |         `+-        |   |  |
                    |                   |                     |          +---------+   |  |
                    |                   |                     |                        |  |
                    |                   |               +-----+--+                +----+--+-+ 
                    |                   |               | Homepi |                | ATA     |
                    |                   |               |        |                | Adapter |
                    |                   |               +--------+                +---------+
....

== Netzwerkdosen

|===
|Standort                      |Links |Rechts

|Sicherungskasten Mieterkeller |2     |1
|Hausanschlusspunkt            |4     |3
|Garderobe EG                  |6     |5
|Flur OG1                      |8     |7
|Schlafzimmer 2. OG            |10    |9
|Wohnzimmer                    |12    |11
|Büro 1. OG 1                  |13    |14
|Büro 1. OG 2                  |--    |15
|===

== Uplink

Der Uplink ist eine DOCSIS Leitung von link:https://www.unitymedia.de/benutzerkonto/login/zugangsdaten[Vodafone] (ehemals Unitymedia).

== Subnezte

Es gibt die folgenden Subnetze:

|===
|Netz-ID |VLAN-ID |Beschreibung                              |IPv4-Subnetz   |IPv6-ULA

|1       |0       |Standard-Netz                             |192.168.1.0/24 |fd6b:b175:9ccf:c1::/64
|2       |30      |IoT-Netz                                  |192.168.2.0/24 |fd6b:b175:9ccf:c2::/64
|3       |040     |Gäste-Netz                                |192.168.3.0/24 |fd6b:b175:9ccf:c3::/64
|4       |041     |Kabelgebundenes Gästenetz                 |192.168.4.0/24 |fd6b:b175:9ccf:c4::/64
|5       |0N/A    |OpenVPN                                   |192.168.5.0/24 |fd6b:b175:9ccf:c5::/64
|6       |050     |xref:services/uplink/fallback.adoc[WAN-Fallback] |192.168.6.0/24 |
|7       |0N/A    |Modem-Netzwerk                            |192.168.7.0/24 |fd6b:b175:9ccf:c7::/64
|8       |080     |xref:k8s::index.adoc[k8s Cluster]       |192.168.8.0/24 |fd6b:b175:9ccf:c8::/64
|===

Details zum IPv6 Setup finden sich auf der Seite xref:ipv6.adoc[IPv6].

== WLAN

Details zum wlan finden sich auf einer extra Seite: xref:services/wifi.adoc[Wifi]

== DNS

Die Domain home.bergmann.click ist bei https://dynv6.com gehostet. Die IPv4 Adresse wird vom Router per ddclient aktualisiert. Um auch die IPv6 Adresse und das deligierte Präfix zu aktualisieren existiert ein zusätzliches link:https://github.com/bergmann-it/edgeos-scripts[Script].

== Hosts

Fast alle Hosts bekommen ihre Adressen per DHCP vergeben. Einige der Geräte bekommen über den DHCP statische Adressen zugewiesen bzw. haben diese statisch konfiguriert. Details zu den konfigurierten hosts finden sich im link:https://gw-1.bergmann.click/[Router].
Unten die wichtigsten Hosts im Überblick:

=== Standard-Netz

|===
|Host                                      |IP                |Dokumentation

|Reserviert                                |192.168.1.1-15    |
|IP für Broardcast MAC für WOL |192.168.1.3      |    |
|DHCP-Bereich                              |192.168.1.16-191  |
|link:https://192.168.1.244/[ATA Adapter]  |192.168.1.244     |xref:services/telefon.adoc[Telefon]
|link:http://192.168.1.245/[Switch]        |192.168.1.245     |
|Homepi                                    |192.168.1.250     |xref:homepi.adoc[Homepi]
|link:https://gw-1.bergmann.click/[Router] |192.168.1.254     |
|=== 

=== WAN-Fallback

|===
|Host                                      |IP                |Dokumentation

|xref:services/uplink/fallback.adoc[WAN-Fallback-Router]                       |192.168.6.1       |
|Router                                    |192.168.6.2       |
|=== 

=== Modem-Netz

|===
|Host                                      |IP                |Dokumentation

|Modem                                     |192.168.7.1       |
|Router                                    |192.168.7.2       |
|=== 

=== Kubernetes Cluster

|===
|Host                                      |IP                |Präfix |Dokumentation

|Reserviert                                |192.168.8.1-15    |/28    |
|link:https://gw-1.bergmann.click/[Router] |192.168.8.1       |/32    |
|IP für Broardcast MAC für WOL |192.168.8.3      |    |
|Master Nodes                              |192.168.8.16-18   |/28    |
|DHCP Bereich für worker nodes             |192.168.8.19-31   |/28    |
|MetalLB                                   |192.168.8.32-63   |/27    |
|Reserviert                                |192.168.8.192-254 |/26    |
|=== 

