= Netzwerk

== Physikalisches Netzwerk
Das Netzwerk in der Frankensteiner Str. 15 ist relativ einfach um den Mittelpunkt im Kellerflur aufgebaut:

[svgbob]
....
------+--------------------------------------------------------------------------------------
2. OG |                                          
------'                                               
                                               
------+---------------------------------+-+------+-------------------+-+------+--------------
1. OG |                                 | | Flur | +-----------+     | | Büro | +-------+
------'                                 | '------' | AP        |     | '------' | DECT  |
                                        |          | 1. OG     +---. | .--O     | Basis +--.
                                        |          +-----------+   | | |        +-------+  |
---+------------------------------------+--------------------------+-+-+-------------------+-
EG |                                               +-----------+   |   |                   |
---'                                               | AP        |   |   |                   |
                                                   | Garderobe +-. |   |                   |
                                                   +-----------+ | |   |                   |
-------+------------+-+--------------+---+-+------+--------------+-+---+-------------------+-
Keller |            | | Heizungsraum |   | | Flur |              | |   |                   |
-------'            | '--------------'   | '------'              | |   |                   |
    .-,(  ),-.      |    +--------+      |     +--------------+  | |   |                   |
 .-(          )-.   |    | DOCSIS |      |     |   Router     |  | |   |                   |
(    internet    )--+----+ Modem  |      |    ,+-            -+. | |   |   +---------+     |
 '-(          ).-'  |    |        +------+----+ eth0      eth4 +-' |   |   | Switch  |     |
     '-.( ).-'      |    +--------+      |    `+-         eth3 +---'   |   |         |     |
                    |                    |     |          eth1 +-------'  ,+-       -+.    |
                    |                    |     |          eth2 +----------+ port0     +--. |
                    |                    |     |             -+'       .--+ port1   -+'  | |
                    |                    |     +--------------+        |  `+-        |   | |
                    |                    |                             |   +---------+   | |
                    |                    |                             |                 | |
                    |                    |                       +-----+-----+     +-----+-+-+ 
                    |                    |                       | Homepi    |     | ATA     |
                    |                    |                       |           |     | Adapter |
                    |                    |                       +-----------+     +---------+ 
....

== Netzwerkdosen

|===
|Standort                      |Links |Rechts

|Sicherungskasten Mieterkeller |2     |1
|Hausanschlusspunkt            |4     |3
|Garderobe EG                  |6     |5
|Flur OG1                      |8     |7
|Schlafzimmer 2. OG            |10    |9
|Wohnzimmer                    |12    |11
|Büro 1. OG 1                  |13    |14
|Büro 1. OG 2                  |--    |15
|===

== Uplink

Der Uplink ist eine DOCSIS Leitung von link:https://www.unitymedia.de/benutzerkonto/login/zugangsdaten[Vodafone] (ehemals Unitymedia).

== Subnezte

Es gibt die folgenden Subnetze:

|===
|VLAN-ID |Beschreibung                        |Subnetz

|0       |Standard-Netz                       |192.168.1.0/24
|30      |IoT-Netz                            |192.168.2.0/24
|40      |Gäste-Netz                          |192.168.3.0/24
|41      |Kabelgebundenes Gästenetz           |192.168.4.0/24
|N/A     |OpenVPN                             |192.168.5.0/24
|80      |xref:services/k8s.adoc[k8s Cluster] |192.168.8.0/24
|===

== WLAN

Details zum wlan finden sich auf einer extra Seite: xref:services/wifi.adoc[Wifi]

== Hosts

Fast alle Hosts bekommen ihre Adressen per DHCP vergeben. Einige der Geräte bekommen über den DHCP statische Adressen zugewiesen bzw. haben diese statisch konfiguriert. Details zu den konfigurierten hosts finden sich im link:https://gw-1.bergmann.click/[Router].
Unten die wichtigsten Hosts im Überblick:

=== Standard-Netz

|===
|Host                                      |IP                |Dokumentation

|Reserviert                                |192.168.1.1-15    |
|DHCP-Bereich                              |192.168.1.16-191  |
|link:https://192.168.1.244/[ATA Adapter]  |192.168.1.244     |xref:services/telefon.adoc[Telefon]
|link:http://192.168.1.245/[Switch]        |192.168.1.245     |
|Homepi                                    |192.168.1.250     |xref:homepi.adoc[Homepi]
|link:https://gw-1.bergmann.click/[Router] |192.168.1.254     |
|=== 

=== Kubernetes Cluster

|===
|Host                                      |IP                |Präfix |Dokumentation

|Reserviert                                |192.168.8.1-15    |/28    |
|link:https://gw-1.bergmann.click/[Router] |192.168.8.1       |/32    |
|Master Nodes                              |192.168.8.8-15    |/29    |
|DHCP Bereich für worker nodes             |192.168.8.16-31   |/28    |
|MetalLB                                   |192.168.8.32-63   |/27    |
|Reserviert                                |192.168.8.192-254 |/26    |
|=== 

