= Netzwerk

== Physikalisches Netzwerk
Das Netzwerk in der Frankensteiner Str. 15 ist relativ einfach:

[svgbob]
....
------+------------------------------------------------------------------------------------
2. OG |                                          
------'                                               
                                               
------+----------------------------------+-+------+------------------+-+------+-------------
1. OG |                                  | | Flur | +-----------+    | | Büro | +-------+
------'                                  | '------' | AP        |    | '------' | DECT  |
                                         |          | 1. OG     +--. |          | Basis +-.
                                         |          +-----------+  | |          +-------+ |
---+-------------------------------------+-------------------------+-+--------------------+-
EG |                                           +-----------+       |                      |
---'                                           | AP        |       |                      |
                                               | Garderobe +-----. |                      |
                                               +-----------+     | |                      |
-------+------------+-+--------------+---+-+------+--------------+-+----------------------+-
Keller |            | | Heizungsraum |   | | Flur |              | |                      |
-------'            | '--------------'   | '------'              | |                      |
    .-,(  ),-.      |    +--------+      |     +-------------+   | |                      |
 .-(          )-.   |    | DOCSIS |      |     |   Router    |   | |                      |
(    internet    )--+----+ Modem  |      |    ,+-    --------+-. | |    +---------+       |
 '-(          ).-'  |    |        +------+----| eth0 vlan eth1 +-' |    | Switch  |       |
     '-.( ).-'      |    +--------+      |    `+-    0u   eth2 +---'   ,+-       -+,      |
                    |                    |     |     ,30t eth3 +-------+ port0     +-.    |
                    |                    |     |     ,40t eth4 +-.     `+-       -+' |    |
                    |                    |     |     -------+--' |      +---------+  |    |
                    |                    |     |            |    |                   |    |
                    |                    |     +------------+  +-+---------+     +---+----++
                    |                    |                     | Raspberry |     | ATA     |
                    |                    |                     | Pi        |     | Adapter |
                    |                    |                     +-----------+     +---------+

Legende:
---------
vlan:
 u untagged
 t tagged
....

== Uplink

Der Uplink ist eine DOCSIS Leitung von link:https://www.unitymedia.de/benutzerkonto/login/zugangsdaten[Vodafone] (ehemals Unitymedia).

== Subnezte

Es gibt die folgenden Subnetze:

|===
|VLAN-ID |Beschreibung  |Subnetz

|0       |Standard-Netz             |192.168.1.0/24
|30      |IoT-Netz                  |192.168.2.0/24
|40      |Gäste-Netz                |192.168.3.0/24
|41      |Kabelgebundenes Gästenetz |192.168.4.0/24
|N/A     |OpenVPN                   |192.168.5.0/24

|===

== WLAN

Details zum wlan finden sich auf einer extra Seite: xref:services/wifi.adoc[Wifi]

== Hosts

Fast alle Hosts bekommen ihre Adressen per DHCP vergeben. Einige der Geräte bekommen über den DHCP statische Adressen zugewiesen bzw. haben diese statisch konfiguriert. Details zu den konfigurierten hosts finden sich im link:https://gw-1.bergmann.click/[Router].
Unten die wichtigsten Hosts im Überblick:

|===
|Host                                      |IP            |Dokumentation

|link:https://gw-1.bergmann.click/[Router] |192.168.1.254 |
|link:https://192.168.1.244/[ATA Adapter]  |192.168.1.244 |
|Homepi                                    |192.168.1.250 |xref:homepi.adoc[Homepi]
|link:http://192.168.1.245/[Switch]        |192.168.1.245 |

|=== 
